//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from CSV_8_1.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CSV_8_1Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface ICSV_8_1Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSV_8_1Parser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] CSV_8_1Parser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSV_8_1Parser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] CSV_8_1Parser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSV_8_1Parser.hdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterHdr([NotNull] CSV_8_1Parser.HdrContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSV_8_1Parser.hdr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitHdr([NotNull] CSV_8_1Parser.HdrContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CSV_8_1Parser.row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRow([NotNull] CSV_8_1Parser.RowContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CSV_8_1Parser.row"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRow([NotNull] CSV_8_1Parser.RowContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Text</c>
	/// labeled alternative in <see cref="CSV_8_1Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterText([NotNull] CSV_8_1Parser.TextContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Text</c>
	/// labeled alternative in <see cref="CSV_8_1Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitText([NotNull] CSV_8_1Parser.TextContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="CSV_8_1Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] CSV_8_1Parser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="CSV_8_1Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] CSV_8_1Parser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="CSV_8_1Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmpty([NotNull] CSV_8_1Parser.EmptyContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Empty</c>
	/// labeled alternative in <see cref="CSV_8_1Parser.field"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmpty([NotNull] CSV_8_1Parser.EmptyContext context);
}
