//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from LispStyleTree.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public partial class LispStyleTreeParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, ID=4;
	public const int
		RULE_parent_node = 0, RULE_child_node = 1;
	public static readonly string[] ruleNames = {
		"parent_node", "child_node"
	};

	private static readonly string[] _LiteralNames = {
		null, "'('", "' '", "')'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, "ID"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "LispStyleTree.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static LispStyleTreeParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public LispStyleTreeParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public LispStyleTreeParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class Parent_nodeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LispStyleTreeParser.ID, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public Child_nodeContext[] child_node() {
			return GetRuleContexts<Child_nodeContext>();
		}
		[System.Diagnostics.DebuggerNonUserCode] public Child_nodeContext child_node(int i) {
			return GetRuleContext<Child_nodeContext>(i);
		}
		public Parent_nodeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parent_node; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILispStyleTreeListener typedListener = listener as ILispStyleTreeListener;
			if (typedListener != null) typedListener.EnterParent_node(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILispStyleTreeListener typedListener = listener as ILispStyleTreeListener;
			if (typedListener != null) typedListener.ExitParent_node(this);
		}
	}

	[RuleVersion(0)]
	public Parent_nodeContext parent_node() {
		Parent_nodeContext _localctx = new Parent_nodeContext(Context, State);
		EnterRule(_localctx, 0, RULE_parent_node);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 4;
			Match(T__0);
			State = 5;
			Match(ID);
			State = 8;
			ErrorHandler.Sync(this);
			_alt = 1+1;
			do {
				switch (_alt) {
				case 1+1:
					{
					{
					State = 6;
					Match(T__1);
					State = 7;
					child_node();
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 10;
				ErrorHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(TokenStream,0,Context);
			} while ( _alt!=1 && _alt!=global::Antlr4.Runtime.Atn.ATN.INVALID_ALT_NUMBER );
			State = 12;
			Match(T__2);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class Child_nodeContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public Parent_nodeContext parent_node() {
			return GetRuleContext<Parent_nodeContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ID() { return GetToken(LispStyleTreeParser.ID, 0); }
		public Child_nodeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_child_node; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override void EnterRule(IParseTreeListener listener) {
			ILispStyleTreeListener typedListener = listener as ILispStyleTreeListener;
			if (typedListener != null) typedListener.EnterChild_node(this);
		}
		[System.Diagnostics.DebuggerNonUserCode]
		public override void ExitRule(IParseTreeListener listener) {
			ILispStyleTreeListener typedListener = listener as ILispStyleTreeListener;
			if (typedListener != null) typedListener.ExitChild_node(this);
		}
	}

	[RuleVersion(0)]
	public Child_nodeContext child_node() {
		Child_nodeContext _localctx = new Child_nodeContext(Context, State);
		EnterRule(_localctx, 2, RULE_child_node);
		try {
			State = 16;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				EnterOuterAlt(_localctx, 1);
				{
				State = 14;
				parent_node();
				}
				break;
			case ID:
				EnterOuterAlt(_localctx, 2);
				{
				State = 15;
				Match(ID);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,4,19,2,0,7,0,2,1,7,1,1,0,1,0,1,0,1,0,4,0,9,8,0,11,0,12,0,10,1,0,1,
		0,1,1,1,1,3,1,17,8,1,1,1,1,10,0,2,0,2,0,0,18,0,4,1,0,0,0,2,16,1,0,0,0,
		4,5,5,1,0,0,5,8,5,4,0,0,6,7,5,2,0,0,7,9,3,2,1,0,8,6,1,0,0,0,9,10,1,0,0,
		0,10,11,1,0,0,0,10,8,1,0,0,0,11,12,1,0,0,0,12,13,5,3,0,0,13,1,1,0,0,0,
		14,17,3,0,0,0,15,17,5,4,0,0,16,14,1,0,0,0,16,15,1,0,0,0,17,3,1,0,0,0,2,
		10,16
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
