//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JSON_8_2.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IJSON_8_2Listener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class JSON_8_2BaseListener : IJSON_8_2Listener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSON_8_2Parser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterJson([NotNull] JSON_8_2Parser.JsonContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSON_8_2Parser.json"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitJson([NotNull] JSON_8_2Parser.JsonContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>AnObject</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAnObject([NotNull] JSON_8_2Parser.AnObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>AnObject</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAnObject([NotNull] JSON_8_2Parser.AnObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyObject</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyObject([NotNull] JSON_8_2Parser.EmptyObjectContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyObject</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.object"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyObject([NotNull] JSON_8_2Parser.EmptyObjectContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSON_8_2Parser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPair([NotNull] JSON_8_2Parser.PairContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSON_8_2Parser.pair"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPair([NotNull] JSON_8_2Parser.PairContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayOfValues</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayOfValues([NotNull] JSON_8_2Parser.ArrayOfValuesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayOfValues</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayOfValues([NotNull] JSON_8_2Parser.ArrayOfValuesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyArray</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEmptyArray([NotNull] JSON_8_2Parser.EmptyArrayContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyArray</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.array"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEmptyArray([NotNull] JSON_8_2Parser.EmptyArrayContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterString([NotNull] JSON_8_2Parser.StringContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitString([NotNull] JSON_8_2Parser.StringContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>Atom</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAtom([NotNull] JSON_8_2Parser.AtomContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>Atom</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAtom([NotNull] JSON_8_2Parser.AtomContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ObjectValue</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterObjectValue([NotNull] JSON_8_2Parser.ObjectValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ObjectValue</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitObjectValue([NotNull] JSON_8_2Parser.ObjectValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayValue</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArrayValue([NotNull] JSON_8_2Parser.ArrayValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayValue</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArrayValue([NotNull] JSON_8_2Parser.ArrayValueContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
