//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from JSON_8_2.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="JSON_8_2Parser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IJSON_8_2Listener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSON_8_2Parser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterJson([NotNull] JSON_8_2Parser.JsonContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSON_8_2Parser.json"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitJson([NotNull] JSON_8_2Parser.JsonContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>AnObject</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAnObject([NotNull] JSON_8_2Parser.AnObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>AnObject</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAnObject([NotNull] JSON_8_2Parser.AnObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyObject</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyObject([NotNull] JSON_8_2Parser.EmptyObjectContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyObject</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.object"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyObject([NotNull] JSON_8_2Parser.EmptyObjectContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="JSON_8_2Parser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPair([NotNull] JSON_8_2Parser.PairContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="JSON_8_2Parser.pair"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPair([NotNull] JSON_8_2Parser.PairContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayOfValues</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayOfValues([NotNull] JSON_8_2Parser.ArrayOfValuesContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayOfValues</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayOfValues([NotNull] JSON_8_2Parser.ArrayOfValuesContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>EmptyArray</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEmptyArray([NotNull] JSON_8_2Parser.EmptyArrayContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>EmptyArray</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.array"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEmptyArray([NotNull] JSON_8_2Parser.EmptyArrayContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterString([NotNull] JSON_8_2Parser.StringContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>String</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitString([NotNull] JSON_8_2Parser.StringContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Atom</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAtom([NotNull] JSON_8_2Parser.AtomContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Atom</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAtom([NotNull] JSON_8_2Parser.AtomContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ObjectValue</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterObjectValue([NotNull] JSON_8_2Parser.ObjectValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ObjectValue</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitObjectValue([NotNull] JSON_8_2Parser.ObjectValueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayValue</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayValue([NotNull] JSON_8_2Parser.ArrayValueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayValue</c>
	/// labeled alternative in <see cref="JSON_8_2Parser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayValue([NotNull] JSON_8_2Parser.ArrayValueContext context);
}
