//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from VecMsg.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="VecMsgParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface IVecMsgListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="VecMsgParser.vec4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVec4([NotNull] VecMsgParser.Vec4Context context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VecMsgParser.vec4"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVec4([NotNull] VecMsgParser.Vec4Context context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="VecMsgParser.ints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInts([NotNull] VecMsgParser.IntsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="VecMsgParser.ints"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInts([NotNull] VecMsgParser.IntsContext context);
}
