//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Cymbol.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CymbolParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public interface ICymbolListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CymbolParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFile([NotNull] CymbolParser.FileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CymbolParser.file"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFile([NotNull] CymbolParser.FileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CymbolParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDecl([NotNull] CymbolParser.VarDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CymbolParser.varDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDecl([NotNull] CymbolParser.VarDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CymbolParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] CymbolParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CymbolParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] CymbolParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CymbolParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDecl([NotNull] CymbolParser.FunctionDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CymbolParser.functionDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDecl([NotNull] CymbolParser.FunctionDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CymbolParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameters([NotNull] CymbolParser.FormalParametersContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CymbolParser.formalParameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameters([NotNull] CymbolParser.FormalParametersContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CymbolParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFormalParameter([NotNull] CymbolParser.FormalParameterContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CymbolParser.formalParameter"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFormalParameter([NotNull] CymbolParser.FormalParameterContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CymbolParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] CymbolParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CymbolParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] CymbolParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CymbolParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStat([NotNull] CymbolParser.StatContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CymbolParser.stat"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStat([NotNull] CymbolParser.StatContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CymbolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpr([NotNull] CymbolParser.ExprContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CymbolParser.expr"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpr([NotNull] CymbolParser.ExprContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CymbolParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExprList([NotNull] CymbolParser.ExprListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CymbolParser.exprList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExprList([NotNull] CymbolParser.ExprListContext context);
}
