//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.11.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from IP_Lexer.g4 by ANTLR 4.11.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using System;
using System.IO;
using System.Text;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.11.1")]
[System.CLSCompliant(false)]
public partial class IP_LexerLexer : Lexer {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		IP=1, INT=2, STRING=3, NL=4, WS=5;
	public static string[] channelNames = {
		"DEFAULT_TOKEN_CHANNEL", "HIDDEN"
	};

	public static string[] modeNames = {
		"DEFAULT_MODE"
	};

	public static readonly string[] ruleNames = {
		"IP", "INT", "STRING", "NL", "WS"
	};


	public IP_LexerLexer(ICharStream input)
	: this(input, Console.Out, Console.Error) { }

	public IP_LexerLexer(ICharStream input, TextWriter output, TextWriter errorOutput)
	: base(input, output, errorOutput)
	{
		Interpreter = new LexerATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	private static readonly string[] _LiteralNames = {
	};
	private static readonly string[] _SymbolicNames = {
		null, "IP", "INT", "STRING", "NL", "WS"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "IP_Lexer.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string[] ChannelNames { get { return channelNames; } }

	public override string[] ModeNames { get { return modeNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static IP_LexerLexer() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}
	private static int[] _serializedATN = {
		4,0,5,42,6,-1,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,1,0,1,0,1,0,1,0,
		1,0,1,0,1,0,1,0,1,1,4,1,21,8,1,11,1,12,1,22,1,2,1,2,5,2,27,8,2,10,2,12,
		2,30,9,2,1,2,1,2,1,3,3,3,35,8,3,1,3,1,3,1,4,1,4,1,4,1,4,1,28,0,5,1,1,3,
		2,5,3,7,4,9,5,1,0,2,1,0,48,57,2,0,9,9,32,32,44,0,1,1,0,0,0,0,3,1,0,0,0,
		0,5,1,0,0,0,0,7,1,0,0,0,0,9,1,0,0,0,1,11,1,0,0,0,3,20,1,0,0,0,5,24,1,0,
		0,0,7,34,1,0,0,0,9,38,1,0,0,0,11,12,3,3,1,0,12,13,5,46,0,0,13,14,3,3,1,
		0,14,15,5,46,0,0,15,16,3,3,1,0,16,17,5,46,0,0,17,18,3,3,1,0,18,2,1,0,0,
		0,19,21,7,0,0,0,20,19,1,0,0,0,21,22,1,0,0,0,22,20,1,0,0,0,22,23,1,0,0,
		0,23,4,1,0,0,0,24,28,5,34,0,0,25,27,9,0,0,0,26,25,1,0,0,0,27,30,1,0,0,
		0,28,29,1,0,0,0,28,26,1,0,0,0,29,31,1,0,0,0,30,28,1,0,0,0,31,32,5,34,0,
		0,32,6,1,0,0,0,33,35,5,13,0,0,34,33,1,0,0,0,34,35,1,0,0,0,35,36,1,0,0,
		0,36,37,5,10,0,0,37,8,1,0,0,0,38,39,7,1,0,0,39,40,1,0,0,0,40,41,6,4,0,
		0,41,10,1,0,0,0,4,0,22,28,34,1,6,0,0
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
