// This grammar is identical to PropertyFile_7_2
// (it has been copied here to show clearly the difference in the files generated by ANTLR)
grammar PropertyFile_7_3;

file	:	prop+ ;
prop	:	ID '=' STRING NEWLINE ;

ID		:	[a-z]+ ;
STRING	:	'"' .*? '"' ;
NEWLINE	:	'\r'? '\n' ; 